// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA8YFIVhU4RBHvOok61G4BNhu40Y1nGxc',
    appId: '1:788083821973:web:0e6021353f07a73b9d3a9c',
    messagingSenderId: '788083821973',
    projectId: 'prototype-80b6e',
    authDomain: 'prototype-80b6e.firebaseapp.com',
    databaseURL: 'https://prototype-80b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prototype-80b6e.appspot.com',
    measurementId: 'G-DV63LVNQQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCaOtkR4tcfVPrBt_oQOPTlR1Eg6i-_0A',
    appId: '1:788083821973:android:4c22bc0a7989e2209d3a9c',
    messagingSenderId: '788083821973',
    projectId: 'prototype-80b6e',
    databaseURL: 'https://prototype-80b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prototype-80b6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwE0LMx-VQXJVzdx-5BXKa79QXfBc7tc',
    appId: '1:788083821973:ios:1b53c584ef6eb2439d3a9c',
    messagingSenderId: '788083821973',
    projectId: 'prototype-80b6e',
    databaseURL: 'https://prototype-80b6e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prototype-80b6e.appspot.com',
    iosClientId: '788083821973-8o3q6eg1u2ujgpo93q6dsb7p3hnrif8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.teratesejahtera',
  );
}
